### ISSUE TITLE
panic: InvalidEndpointURL: invalid endpoint uri

### ISSUE THREAD

**Issue by sandile-yakka** [nabsul/k8s-ecr-login-renew#12]
Hi,

I'm just testing out your tool following the  instructions on Readme, I'm running this on K3s and trying to connect ECR in the af-south-1 region but I'm getting InvalidEndpointURL error. Here are the logs from the pod:

panic: InvalidEndpointURL: invalid endpoint uri
caused by: parse "https://api.ecr.af-south-1\n.amazonaws.com/": net/url: invalid control character in URL

goroutine 1 [running]:
main.checkErr(...)
	/app/main.go:19
main.main()
	/app/main.go:38 +0x7b7
Fetching auth data from AWS... % 

Is this a me issue or is this something that you could perhaps assist in resolving?

Thanks for your help in advance.

**Comment by nabsul** [comment]
It looks like it's both a "you" problem and something I can help you with :-)

It looks like you have a `\n` (new line character) at the end of your region name. I suspect removing that will solve your problem.

**Comment by sandile-yakka** [comment]
ah I see :)

Thanks, the issue was that new line character.
