### ISSUE TITLE
Using TARGET_NAMESPACE with ns not in the Role

### ISSUE THREAD

**Issue by IJOL** [nabsul/k8s-ecr-login-renew#13]
We are rookies in  k8s, and this may be a general k8s question, but we plan to use your nice, little thing, and we wonder if we need to grant more permissions to the Role to be able to create secrets in all the namespaces we put in TARGET_NAMESPACES...

**Comment by nabsul** [comment]
Hi, you might want to double check in the kubernetes docs in case there's a better way, but as far as I know you have two options:

1) If you want to just grant the tool access to a few namespaces, you can create a Role and RolBinding for each namespace (and attach all of them to the same service account)

2) If you want to grant access to all namespaces, you can use ClusterRole and ClusterRoleBinding instead. These are similar to Role and RoleBinding, but they apply across all namespaces.

Hope that helps.
