### ISSUE TITLE
Annotations are lost when the new secret is created

### ISSUE THREAD

**Issue by xavidop** [nabsul/k8s-ecr-login-renew#15]
Hello,

I was noticed that the metadata is lost when the new secret is created.

**Comment by nabsul** [comment]
This is by design. The tool always deletes the existing secret and recreates it. 

But I'm open to changing the behaviour if it doesn't have any downsides.

**Comment by xavidop** [comment]
I think the only change that has to be done is the content of the secret. The other data could be important like in my case. I have some key annotations. Ones added automatically by helm and another ones used by Replicator to replicate a secret in multiple namespaces. What do you think?

**Comment by nabsul** [comment]
Sounds reasonable to me. It should be a small change. I'll try to get it done this weekend or next.

**Comment by xavidop** [comment]
Okay!
Thank you so for your understanding!

**Comment by nabsul** [comment]
v1.4 is getting published shortly. Be sure to grant "update" permissions to the service account so that it can perform this new operation.
