### ISSUE TITLE
[Question] What's the use case of this project compared to amazon-ecr-credential-helper?

### ISSUE THREAD

**Issue by PawelLipski** [nabsul/k8s-ecr-login-renew#21]
https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/ => `Amazon ECR Docker Credential Helper`

Actually, how does this project relate to the Helper? Is Helper for some reason not easy to use for k8s authentication against ECR? 🤔

**Comment by nabsul** [comment]
Interesting find, I've never heard of this tool before. Looking at the blog post and the [documentation](https://github.com/awslabs/amazon-ecr-credential-helper), `amazon-ecr-credential-helper` appears to be specifically designed to save you from typing `docker login` (on your local machine or in your CI/CD pipeline). So it's specifically designed for Docker. 

`k8s-ecr-login-renew` is specifically designed for Kubernetes. It fetches the ECR registry credentials and saves them to a K8s secret. It essentially automates the process described [here](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html) and [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).

**Comment by PawelLipski** [comment]
Ok, that's what I suspected as well, thanks
