### ISSUE TITLE
:latest is not on dockerhub anymore

### ISSUE THREAD

**Issue by cristianrat** [nabsul/k8s-ecr-login-renew#54]
Thanks for this package, been using it for a long time
Just noticed latest is no longer on docker hub.
Not sure if that's intentional or not, however, latest is pretty standard to always be there

**Comment by cristianrat** [comment]
So it's entirely my fault for using latest (which in the end cause my nodes to fail, because they're unable to pull images from ECR - that's on me for using a shoestring setup)
Also got another issue with using main, which is 3 hours old:
Unsure if it's me or not, thought i'd raise the issue
```panic: namespaces is forbidden: User "system:serviceaccount:MYNAMESPACE:svc-ecr-renew" cannot list resource "namespaces" in API group "" at the cluster scope

goroutine 1 [running]:
main.checkErr(...)
	/go/src/app/main.go:22
main.main()
	/go/src/app/main.go:45 +0x5da
```

**Comment by nabsul** [comment]
Hi there. Regarding `latest` I used to generate it, but I'm not really in favor of this practice. It's better for both you and me if you commit to a specific version and upgrade intentionally. This allows me to experiment more easily and ship new features.

Regarding the error message, which version of the tool were you using? And were there any additional details in the error message?

**Comment by cristianrat** [comment]
fair enough, I've switched to 1.7.1

the error comes from "main"
so I guess it's the one from 3 hours ago

**Comment by nabsul** [comment]
I think the word main there is referring to the main function, not the main branch of git. If you were previously on `latest`, you were probably using a much older version of the tool.

Is there any more text before or after the lines of output you shared?

**Comment by cristianrat** [comment]
the word main may be referring to the function, but it was the main tag from github :)
probably old, don't know, but it works for me
so now using 1.7.1 which also works, so will stick with that

the text before was reporting success in getting the credentials, and there was no message after

**Comment by nabsul** [comment]
Oh! I think I know what went wrong, you were probably previously using a version that didn't handle namespaces the way the latest version did. Now you're trying to use the latest version, and it requires permission to list all namespaces in your cluster.

I probably should have just kept latest but never updated it. Deleting was a mistake on my part as I was cleaning out a bunch of experimental images.

However, maybe it's worthwhile to just go through the readme and get yourself acquainted with the features of the latest version? :-)

**Comment by cristianrat** [comment]
fair enough
Yeah, I need to provide the namespace to write to (hence not trying to write)
Will check what the new version has to offer
👍 
thanks
