### ISSUE TITLE
standard_init_linux.go:211: exec user process caused “exec format error” on K3s running on ARM

### ISSUE THREAD

**Issue by kuskoman** [nabsul/k8s-ecr-login-renew#9]
Running job using file from #8 results in
```
standard_init_linux.go:211: exec user process caused “exec format error”
```

when using K3s on arm devices (raspberry and orange pi, both failing)

**Comment by nabsul** [comment]
This would require the tool be rebuilt to an ARM version. I'd be happy to look into it, but it might take some time.

If you'd like contribute to this project that would also be highly appreciated :-)

**Comment by nabsul** [comment]
Hey! Can you try this version of the tool? `nabsul/k8s-ecr-login-renew:arm-v0.01`

**Comment by nabsul** [comment]
@kuskoman From v1.3 onwards I'll be pushing both x64 and ARM versions of the docker image. You now use: `nabsul/k8s-ecr-login-renew:arm32v7-v1.3`.

I'll keep the test version `nabsul/k8s-ecr-login-renew:arm-v0.01` up for a while longer, but you should expect it to get deleted at some point in the future.
